### ISSUE TITLE
Stop at Alien Worlds login screen

### ISSUE THREAD

**Issue by jpedro06** [anonieX/alienworldsauto#4]
Works normally until you reach the login screen

https://imgur.com/a/AOnvbHW

**Comment by jpedro06** [comment]
I believe the problem is in the move_by_offset, but I don't know how to find the correct one. Does the entire desktop count or just the browser window?

**Comment by filipmagula** [comment]
Open the devtools in Brave  (F12) and set the size of the window to 925x982. Seems working well, but for exact numbers we need to wait for anonieX comment.

https://github.com/anonieX/alienworldsauto/discussions/3

**Comment by cpegasus2** [comment]
Sorry for the question, but how do I set the size of the window to 925x982? I have very little experience coding and don't know how to do it using the devtools... I have the same issue than jpedro06, it works normally if I have the devtools open but it freezes once I reach the alienworlds login screen

**Comment by anonieX** [comment]
> I believe the problem is in the move_by_offset, but I don't know how to find the correct one. Does the entire desktop count or just the browser window?

Hi, it counts just for the browser window. There is no good way to account for any resolution as far as I know. Not resizing the window should do the trick. 929 x 1012 is the default window size, it or anything close will work.

**Comment by anonieX** [comment]
> Sorry for the question, but how do I set the size of the window to 925x982? I have very little experience coding and don't know how to do it using the devtools... I have the same issue than jpedro06, it works normally if I have the devtools open but it freezes once I reach the alienworlds login screen

Hey, if you don't resize the window at all after it appears it should be working. Otherwise you can use http://howbigismybrowser.com/ to set your browser to 929 x 1012 or anything close. Let me know if the default open size is different

**Comment by anonieX** [comment]
I just uploaded a new version that has this issue patched. Let me know if it works.

**Comment by cpegasus2** [comment]
> Hey, if you don't resize the window at all after it appears it should be working. Otherwise you can use http://howbigismybrowser.com/ to set your browser to 929 x 1012 or anything close. Let me know if the default open size is different

Thanks for your time! Now it appears to be working without opening devtools but it still freezes at alienworlds login. My default open size is 937x664 according to http://howbigismybrowser.com/ I cannot resize it to more than 929x768 since I am using a TV screen.

**Comment by anonieX** [comment]
> > Hey, if you don't resize the window at all after it appears it should be working. Otherwise you can use http://howbigismybrowser.com/ to set your browser to 929 x 1012 or anything close. Let me know if the default open size is different
> 
> Thanks for your time! Now it appears to be working without opening devtools but it still freezes at alienworlds login. My default open size is 937x664 according to http://howbigismybrowser.com/ I cannot resize it to more than 929x768 since I am using a TV screen.

Alright, I'll make a "Any Resolution"-friendly version today. Thanks for the issue submit

**Comment by anonieX** [comment]
> > Hey, if you don't resize the window at all after it appears it should be working. Otherwise you can use http://howbigismybrowser.com/ to set your browser to 929 x 1012 or anything close. Let me know if the default open size is different
> 
> Thanks for your time! Now it appears to be working without opening devtools but it still freezes at alienworlds login. My default open size is 937x664 according to http://howbigismybrowser.com/ I cannot resize it to more than 929x768 since I am using a TV screen.

Have you tried version 1.1.1? It will resize to that size automatically, please try it and let me know

**Comment by cpegasus2** [comment]
> Have you tried version 1.1.1? It will resize to that size automatically, please try it and let me know

I redownloaded it just in case and tried it and my window size is still 937x664 according to http://howbigismybrowser.com/ 

It seems to be working without devtools but it still freezes at alienworlds login for me

**Comment by anonieX** [comment]
> > Have you tried version 1.1.1? It will resize to that size automatically, please try it and let me know
> 
> I redownloaded it just in case and tried it and my window size is still 937x664 according to http://howbigismybrowser.com/
> 
> It seems to be working without devtools but it still freezes at alienworlds login for me

I found a solution to this, new update will be uploaded later today.

**Comment by jpedro06** [comment]
In my case, I managed to make it work by changing the height offset by 50 for operation, because in my Brave another bar appears in addition to the bar that says it is an automated test and each bar occupies 50 in height.

I also added an automatic resize when opening the browser.

**Comment by jpedro06** [comment]
> > Have you tried version 1.1.1? It will resize to that size automatically, please try it and let me know
> 
> I redownloaded it just in case and tried it and my window size is still 937x664 according to http://howbigismybrowser.com/
> 
> It seems to be working without devtools but it still freezes at alienworlds login for me

If more than one warning bar is appearing on Brave, adjust the offsets by removing 50 at the height for each bar. In my case there was a bar in addition to the standard one.

**Comment by anonieX** [comment]
> In my case, I managed to make it work by changing the height offset by 50 for operation, because in my Brave another bar appears in addition to the bar that says it is an automated test and each bar occupies 50 in height.
> 
> I also added an automatic resize when opening the browser.

How many bars are there in total? I have 3

**Comment by jpedro06** [comment]
> How many bars are there in total? I have 3

I have 2

**Comment by jpedro06** [comment]
You can use a variable to handle this.

**Comment by cpegasus2** [comment]
I get 3 bars at first but 2 at the login screen.


> > How many bars are there in total? I have 3
> 
> I have 2

I get 3 at first but one closes quickly and so there's only 2 at the alienworlds login screen. I have tried doing what jpedro wrote and adjusting the screen to 937x564 once it's opened by using howbigismybrowser.com and it still freezes at alienworlds login.

**Comment by anonieX** [comment]
Currently working on a new version that will automatically calculate click points. Will be uploaded in about an hour

**Comment by anonieX** [comment]
Hey, version 1.1.2 just came out, it automatically resizes your screen to fit the game and automatically calculates button positions. I tried it on 1920x1200, 1920x1080, 1600x1200 and it always worked. It should work on any 16:9 and 16:9-like screens. Let me know if it works or doesnt work for you! Thanks

https://github.com/anonieX/alienworldsauto/releases/tag/1.1.2

**Comment by vaskhan** [comment]
> Hey, version 1.1.2 just came out, it automatically resizes your screen to fit the game and automatically calculates button positions. I tried it on 1920x1200, 1920x1080, 1600x1200 and it always worked. It should work on any 16:9 and 16:9-like screens. Let me know if it works or doesnt work for you! Thanks
> 
> https://github.com/anonieX/alienworldsauto/releases/tag/1.1.2
It doesn't work for me, at first in the first window when logging in to the wax wallet, he himself could not click on the edit icon for authorization, when he clicked, logged in and again only reached the login on https://play.alienworlds.io/ then no changes, no actions occurred

**Comment by anonieX** [comment]
> > Hey, version 1.1.2 just came out, it automatically resizes your screen to fit the game and automatically calculates button positions. I tried it on 1920x1200, 1920x1080, 1600x1200 and it always worked. It should work on any 16:9 and 16:9-like screens. Let me know if it works or doesnt work for you! Thanks
> > https://github.com/anonieX/alienworldsauto/releases/tag/1.1.2
> > It doesn't work for me, at first in the first window when logging in to the wax wallet, he himself could not click on the edit icon for authorization, when he clicked, logged in and again only reached the login on https://play.alienworlds.io/ then no changes, no actions occurred

What's your screen resolution?

**Comment by vaskhan** [comment]
> > > Hey, version 1.1.2 just came out, it automatically resizes your screen to fit the game and automatically calculates button positions. I tried it on 1920x1200, 1920x1080, 1600x1200 and it always worked. It should work on any 16:9 and 16:9-like screens. Let me know if it works or doesnt work for you! Thanks
> > > https://github.com/anonieX/alienworldsauto/releases/tag/1.1.2
> > > It doesn't work for me, at first in the first window when logging in to the wax wallet, he himself could not click on the edit icon for authorization, when he clicked, logged in and again only reached the login on https://play.alienworlds.io/ then no changes, no actions occurred
> 
> What's your screen resolution?

1366x768

**Comment by anonieX** [comment]
> > > > Hey, version 1.1.2 just came out, it automatically resizes your screen to fit the game and automatically calculates button positions. I tried it on 1920x1200, 1920x1080, 1600x1200 and it always worked. It should work on any 16:9 and 16:9-like screens. Let me know if it works or doesnt work for you! Thanks
> > > > https://github.com/anonieX/alienworldsauto/releases/tag/1.1.2
> > > > It doesn't work for me, at first in the first window when logging in to the wax wallet, he himself could not click on the edit icon for authorization, when he clicked, logged in and again only reached the login on https://play.alienworlds.io/ then no changes, no actions occurred
> > 
> > 
> > What's your screen resolution?
> 
> 1366x768

The only way to fix this is to force a resolution set for everyone. Something like 500x500 because developing for all resolutions is problematic, especially for resolutions this tiny

**Comment by icetooth-sketch** [comment]
> > > > > Hey, version 1.1.2 just came out, it automatically resizes your screen to fit the game and automatically calculates button positions. I tried it on 1920x1200, 1920x1080, 1600x1200 and it always worked. It should work on any 16:9 and 16:9-like screens. Let me know if it works or doesnt work for you! Thanks
> > > > > https://github.com/anonieX/alienworldsauto/releases/tag/1.1.2
> > > > > It doesn't work for me, at first in the first window when logging in to the wax wallet, he himself could not click on the edit icon for authorization, when he clicked, logged in and again only reached the login on https://play.alienworlds.io/ then no changes, no actions occurred
> > > 
> > > 
> > > What's your screen resolution?
> > 
> > 
> > 1366x768
> 
> The only way to fix this is to force a resolution set for everyone. Something like 500x500 because developing for all resolutions is problematic, especially for resolutions this tiny. I'm currently working on that

500x500 best for me, how can I change the resolution myself?

**Comment by vaskhan** [comment]
> > > > > Привет, только что вышла версия 1.1.2, она автоматически изменяет размер экрана в соответствии с игрой и автоматически вычисляет положение кнопок. Я пробовал его на 1920х1200, 1920х1080, 1600х1200, и он всегда работал. Он должен работать на любых экранах формата 16: 9 и 16: 9. Дайте мне знать, работает это для вас или не работает! Спасибо 
> > > > > https://github.com/anonieX/alienworldsauto/releases/tag/1.1.2 
> > > > > У меня не работает, сначала в первом окне при входе в кошелек с воском сам не мог нажать на редактировать значок для авторизации, когда он нажал, вошел в систему и снова дошел только до логина на https://play.alienworlds.io/ то никаких изменений, никаких действий не произошло
> > > 
> > > 
> > > Какое у вас разрешение экрана?
> > 
> > 
> > Полный размер - 1366x768
> 
> Единственный способ исправить это - установить разрешение для всех. Что-то вроде 500x500, потому что разработка для всех разрешений проблематична, особенно для таких крошечных разрешений.

I think it won't be a problem to have a resolution of 500 by 500 if it can run in the background or minimized. It can also work behind other windows, right?

**Comment by cpegasus2** [comment]
I've been testing the new version (1.1.2) and at least for me it only logs into wax cloud wallet once I open devtools using F12. Afterwards it works but it still freezes at Alienworlds login. The screen resolution is set to 1372x584 according to http://howbigismybrowser.com/

**Comment by anonieX** [comment]
> > > > > > Hey, version 1.1.2 just came out, it automatically resizes your screen to fit the game and automatically calculates button positions. I tried it on 1920x1200, 1920x1080, 1600x1200 and it always worked. It should work on any 16:9 and 16:9-like screens. Let me know if it works or doesnt work for you! Thanks
> > > > > > https://github.com/anonieX/alienworldsauto/releases/tag/1.1.2
> > > > > > It doesn't work for me, at first in the first window when logging in to the wax wallet, he himself could not click on the edit icon for authorization, when he clicked, logged in and again only reached the login on https://play.alienworlds.io/ then no changes, no actions occurred
> > > > 
> > > > 
> > > > What's your screen resolution?
> > > 
> > > 
> > > 1366x768
> > 
> > 
> > The only way to fix this is to force a resolution set for everyone. Something like 500x500 because developing for all resolutions is problematic, especially for resolutions this tiny. I'm currently working on that
> 
> 500x500 best for me, how can I change the resolution myself?

You can't yet, working on a new version right now

**Comment by anonieX** [comment]
Please wait for the new version, everyting will be fixed there

**Comment by vaskhan** [comment]
> Please wait for the new version, everyting will be fixed there

by some miracle, the script worked a little, but before the first mining. you get an error about another transaction, as a result, you can't mine automatically

**Comment by jpedro06** [comment]
> Hey, version 1.1.2 just came out, it automatically resizes your screen to fit the game and automatically calculates button positions. I tried it on 1920x1200, 1920x1080, 1600x1200 and it always worked. It should work on any 16:9 and 16:9-like screens. Let me know if it works or doesnt work for you! Thanks
> 
> https://github.com/anonieX/alienworldsauto/releases/tag/1.1.2

It worked for me, but I still had to adjust the height of the miner function. I changed the divisor to 4.22.

**It was a great idea to add these dividers, congratulations.**

**Comment by vaskhan** [comment]
> > Привет, только что вышла версия 1.1.2, она автоматически изменяет размер экрана в соответствии с игрой и автоматически вычисляет положение кнопок. Я пробовал его на 1920x1200, 1920x1080, 1600x1200, и он всегда работал. Он должен работать на любых экранах формата 16: 9 и 16: 9. Дайте мне знать, работает это для вас или не работает! Спасибо
> > https://github.com/anonieX/alienworldsauto/releases/tag/1.1.2
> 
> У меня это сработало, но мне все равно пришлось отрегулировать высоту функции майнера. Я поменял делитель на 4,22.
> 
> **Поздравления, добавить эти разделители было отличной идеей.**

Do you have everything fully working? he starts mining himself, takes the reward himself, and then starts again? Are you not taking part in the process at all?

**Comment by vaskhan** [comment]
![image](https://user-images.githubusercontent.com/66561203/114320714-e698d800-9b1f-11eb-9200-85c8a5ba4a9c.png)
After receiving the award, I probably can't click in the right place. Goes to sleep all the time

**Comment by jpedro06** [comment]
> Do you have everything fully working? he starts mining himself, takes the reward himself, and then starts again? Are you not taking part in the process at all?

I had to adjust the position of two clicks.

def miner
`y = driver.get_window_size()["height"]/4.22`

def get
`y = driver.get_window_size()["height"]/1.688`

See if this works for you.

**Comment by anonieX** [comment]
Hey, [1.1.3](https://github.com/anonieX/alienworldsauto/releases/tag/1.1.3) sets the window size to 500x500 automatically so there wont be any click misalignments. There is also a fix for handling multiple infobars at the top

**Comment by vaskhan** [comment]
> Hey, [1.1.3](https://github.com/anonieX/alienworldsauto/releases/tag/1.1.3) sets the window size to 500x500 automatically so there wont be any click misalignments. There is also a fix for handling multiple infobars at the top

![image](https://user-images.githubusercontent.com/66561203/114358328-77e96800-9b7b-11eb-8b2b-9b77d18a4c95.png)
it remains to work around this error

**Comment by vaskhan** [comment]
![image](https://user-images.githubusercontent.com/66561203/114359658-e0851480-9b7c-11eb-889f-f6d6f09ffa5d.png)
and in this window it does not hit the necessary buttons

**Comment by vaskhan** [comment]
In the end, everything is useless because of that error, every time it appears when the script collects the reward

**Comment by anonieX** [comment]
> > Hey, [1.1.3](https://github.com/anonieX/alienworldsauto/releases/tag/1.1.3) sets the window size to 500x500 automatically so there wont be any click misalignments. There is also a fix for handling multiple infobars at the top
> 
> ![image](https://user-images.githubusercontent.com/66561203/114358328-77e96800-9b7b-11eb-8b2b-9b77d18a4c95.png)
> it remains to work around this error

Restart the script, never seen this issue before. Looks like the error is not bot related

**Comment by anonieX** [comment]
[1.1.4](https://github.com/anonieX/alienworldsauto/releases/tag/1.1.4) was just released. It fixes this issue and adds more debugging featues. Please let me know if it works for you, for unrelated issues to click misalignments please open a new issue.

**Comment by icetooth-sketch** [comment]
the script 1,1,4 does not hit the buttons. While version 1.1.0 is stable for me

**Comment by anonieX** [comment]
> the script 1,1,4 does not hit the buttons. While version 1.1.0 is stable for me

Could you please send me the debug.log file?

**Comment by icetooth-sketch** [comment]
> > the script 1,1,4 does not hit the buttons. While version 1.1.0 is stable for me
> 
> Could you please send me the debug.log file?


[debug.log](https://github.com/anonieX/alienworldsauto/files/6296242/debug.log)

I sometimes helped the bot to press buttons, I thought maybe he would go further on his own

**Comment by anonieX** [comment]
> > > the script 1,1,4 does not hit the buttons. While version 1.1.0 is stable for me
> > 
> > 
> > Could you please send me the debug.log file?
> 
> [debug.log](https://github.com/anonieX/alienworldsauto/files/6296242/debug.log)
> 
> I sometimes helped the bot to press buttons, I thought maybe he would go further on his own

Based on the log the script should be working fine, could you run it without helping it click and send that log?

**Comment by jpedro06** [comment]
> > > Hey, [1.1.3](https://github.com/anonieX/alienworldsauto/releases/tag/1.1.3) sets the window size to 500x500 automatically so there wont be any click misalignments. There is also a fix for handling multiple infobars at the top
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/66561203/114358328-77e96800-9b7b-11eb-8b2b-9b77d18a4c95.png)
> > it remains to work around this error
> 
> Restart the script, never seen this issue before. Looks like the error is not bot related

It happened to me a few times.

**Comment by jpedro06** [comment]
> the script 1,1,4 does not hit the buttons. While version 1.1.0 is stable for me

If you have 3 bars use debugBarsAdd = 1

**Comment by icetooth-sketch** [comment]
> > > > the script 1,1,4 does not hit the buttons. While version 1.1.0 is stable for me
> > > 
> > > 
> > > Could you please send me the debug.log file?
> > 
> > 
> > [debug.log](https://github.com/anonieX/alienworldsauto/files/6296242/debug.log)
> > I sometimes helped the bot to press buttons, I thought maybe he would go further on his own
> 
> Based on the log the script should be working fine, could you run it without helping it click and send that log?

[debug.log](https://github.com/anonieX/alienworldsauto/files/6296684/debug.log)

**Comment by anonieX** [comment]
> > > > > the script 1,1,4 does not hit the buttons. While version 1.1.0 is stable for me
> > > > 
> > > > 
> > > > Could you please send me the debug.log file?
> > > 
> > > 
> > > [debug.log](https://github.com/anonieX/alienworldsauto/files/6296242/debug.log)
> > > I sometimes helped the bot to press buttons, I thought maybe he would go further on his own
> > 
> > 
> > Based on the log the script should be working fine, could you run it without helping it click and send that log?
> 
> [debug.log](https://github.com/anonieX/alienworldsauto/files/6296684/debug.log)

How many bars do you see at the top of the window?

**Comment by anonieX** [comment]
> > the script 1,1,4 does not hit the buttons. While version 1.1.0 is stable for me
> 
> If you have 3 bars use debugBarsAdd = 1

The bot will automatically detect it and adjust the value

**Comment by icetooth-sketch** [comment]
> > > > > > the script 1,1,4 does not hit the buttons. While version 1.1.0 is stable for me
> > > > > 
> > > > > 
> > > > > Could you please send me the debug.log file?
> > > > 
> > > > 
> > > > [debug.log](https://github.com/anonieX/alienworldsauto/files/6296242/debug.log)
> > > > I sometimes helped the bot to press buttons, I thought maybe he would go further on his own
> > > 
> > > 
> > > Based on the log the script should be working fine, could you run it without helping it click and send that log?
> > 
> > 
> > [debug.log](https://github.com/anonieX/alienworldsauto/files/6296684/debug.log)
> 
> How many bars do you see at the top of the window?

2-3 and 0 when I disable them, but with the script version 1,1,4 I did not disable them

**Comment by anonieX** [comment]
> > > > > > > the script 1,1,4 does not hit the buttons. While version 1.1.0 is stable for me
> > > > > > 
> > > > > > 
> > > > > > Could you please send me the debug.log file?
> > > > > 
> > > > > 
> > > > > [debug.log](https://github.com/anonieX/alienworldsauto/files/6296242/debug.log)
> > > > > I sometimes helped the bot to press buttons, I thought maybe he would go further on his own
> > > > 
> > > > 
> > > > Based on the log the script should be working fine, could you run it without helping it click and send that log?
> > > 
> > > 
> > > [debug.log](https://github.com/anonieX/alienworldsauto/files/6296684/debug.log)
> > 
> > 
> > How many bars do you see at the top of the window?
> 
> 2-3 and 0 when I disable them, but with the script version 1,1,4 I did not disable them

How did you disable them?

**Comment by icetooth-sketch** [comment]
> > > > > > > > the script 1,1,4 does not hit the buttons. While version 1.1.0 is stable for me
> > > > > > > 
> > > > > > > 
> > > > > > > Could you please send me the debug.log file?
> > > > > > 
> > > > > > 
> > > > > > [debug.log](https://github.com/anonieX/alienworldsauto/files/6296242/debug.log)
> > > > > > I sometimes helped the bot to press buttons, I thought maybe he would go further on his own
> > > > > 
> > > > > 
> > > > > Based on the log the script should be working fine, could you run it without helping it click and send that log?
> > > > 
> > > > 
> > > > [debug.log](https://github.com/anonieX/alienworldsauto/files/6296684/debug.log)
> > > 
> > > 
> > > How many bars do you see at the top of the window?
> > 
> > 
> > 2-3 and 0 when I disable them, but with the script version 1,1,4 I did not disable them
> 
> How did you disable them?


in the first seconds of opening the browser, if later they freeze when the cross is pressed

**Comment by wilkinshui** [comment]
working nicely for previous day on the new version but until now I need to approve the smart contract when click the claim button. (would show up everytime even I use the always approve function).

**Comment by vaskhan** [comment]
and now the captcha has appeared... ( and before that, I had a problem that after the extraction of the reward, the bot went to sleep, woke up and went back to sleep and so on indefinitely
